import type { VercelRequest, VercelResponse } from '@vercel/node';
import { supabaseAdmin } from './_lib/supabase.js';
import { isAuthorized, unauthorized, setCors } from './_lib/auth.js';
import { frontendProfileToDb, frontendCategoryToDb, frontendLocationToDb, frontendContactToDb, frontendArticleToDb } from './_lib/mappers.js';

// Mock data inlined — mirrors src/lib/mockData.ts + src/data/categories.ts.
// (api/ functions cannot import from src/, so the 10-category structure is duplicated here.)
const categories = [
  { id: 'sport-rekreacija-aktiven-zivot',          name: 'Спорт, Рекреација и Активен Живот',          slug: 'sport-rekreacija-aktiven-zivot',          description: 'Фитнес, спортски клубови, рекреација и активен живот.',                icon: 'Dumbbell',      color: 'emerald' },
  { id: 'zabava-nastani-kreativni-uslugi',         name: 'Забава, Настани и Креативни Услуги',         slug: 'zabava-nastani-kreativni-uslugi',         description: 'Фото, видео, детски забави, декорации, музика и културни настани.',     icon: 'PartyPopper',   color: 'yellow' },
  { id: 'obrazovanie-kursevi-razvoj',              name: 'Образование, Курсеви и Развој',              slug: 'obrazovanie-kursevi-razvoj',              description: 'Школи, приватни часови, обуки и развој на вештини.',                     icon: 'GraduationCap', color: 'indigo' },
  { id: 'profesionalni-uslugi-agencii',            name: 'Професионални Услуги и Агенции',            slug: 'profesionalni-uslugi-agencii',            description: 'Сметководство, право, маркетинг, недвижности и деловна поддршка.',       icon: 'Briefcase',     color: 'slate' },
  { id: 'ubavina-nega-wellness',                   name: 'Убавина, Нега и Wellness',                   slug: 'ubavina-nega-wellness',                   description: 'Фризерски, козметички, wellness и естетски услуги.',                     icon: 'Sparkles',      color: 'pink' },
  { id: 'prodavnici-trgovija-lokalni-proizvodi',   name: 'Продавници, Трговија и Локални Производи',   slug: 'prodavnici-trgovija-lokalni-proizvodi',   description: 'Маркети, бутици, техника, декорации и локални производи.',                icon: 'ShoppingBag',   color: 'green' },
  { id: 'hrana-kafulinja-ugostitelstvo',           name: 'Храна, Кафулиња и Угостителство',           slug: 'hrana-kafulinja-ugostitelstvo',           description: 'Ресторани, кафулиња, пекарници, достава и кетеринг.',                     icon: 'Utensils',      color: 'orange' },
  { id: 'avto-moto-transport',                     name: 'Авто-мото и Транспорт',                     slug: 'avto-moto-transport',                     description: 'Авто сервиси, автоделови, перални, такси и транспорт.',                  icon: 'Car',           color: 'red' },
  { id: 'dom-gradba-majstorski-uslugi',            name: 'Дом, Градба и Мајсторски Услуги',            slug: 'dom-gradba-majstorski-uslugi',            description: 'Градба, поправки, ентериер, електрика, водовод и одржување.',            icon: 'Hammer',        color: 'amber' },
  { id: 'zdravstvo-medicina-farmacija',            name: 'Здравство, Медицина и Фармација',            slug: 'zdravstvo-medicina-farmacija',            description: 'Ординации, аптеки, лаборатории, дијагностика и терапија.',               icon: 'HeartPulse',    color: 'blue' },
];

const locations = [
  { id: '1', name: 'Гостивар', slug: 'gostivar' },
];

const contacts = [
  { id: '1', title: 'Итна медицинска помош', category: 'Итни служби', phone: '194', icon: 'Ambulance' },
  { id: '2', title: 'Полиција', category: 'Итни служби', phone: '192', icon: 'ShieldAlert' },
  { id: '3', title: 'Противпожарна служба', category: 'Итни служби', phone: '193', icon: 'Flame' },
  { id: '4', title: 'Општа болница — Гостивар', category: 'Болници', phone: '042 222 333', address: 'ул. Браќа Ѓиноски', icon: 'Hospital' },
  { id: '5', title: 'Општина Гостивар', category: 'Институции', phone: '042 213 511', address: 'Плоштад Гоце Делчев', icon: 'Building' },
];

const articles = [
  { id: '1', title: 'Каде да најдете авто сервис во Гостивар?', slug: 'kade-da-najdete-avto-servis', excerpt: 'Преглед на најдобрите авто сервиси во регионот.', content: '', image_url: 'https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?q=80&w=600&auto=format&fit=crop', created_at: '2023-11-20T10:00:00Z' },
  { id: '2', title: 'Ресторани за семеен ручек во Полог', slug: 'restorani-za-semeen-ruchek', excerpt: 'Нашите препораки за мирен и вкусен неделен ручек.', content: '', image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=600&auto=format&fit=crop', created_at: '2023-11-21T10:00:00Z' },
];

const profiles = [
  { id: '1', name: 'Стоматолошка ординација Д-р Ана', slug: 'stomatoloshka-ordinacija-dr-ana', category: 'Здравство, Медицина и Фармација', categorySlug: 'zdravstvo-medicina-farmacija', subcategory: 'Стоматолошки ординации', location: 'Гостивар', shortDescription: 'Превентивна и реставративна стоматологија.', fullDescription: 'Современ стоматолошки центар во срцето на Гостивар.', phone: '070 123 456', secondaryPhone: '042 555 666', email: 'info@dentalana.mk', website: 'https://dentalana.mk', facebook: 'https://facebook.com/dentalana', instagram: 'https://instagram.com/dentalana_mk', address: 'ул. Илинденска бр. 10', workingHours: 'Пон-Пет: 09:00 - 17:00', googleMapsUrl: 'https://maps.google.com/?q=Gostivar', isFeatured: true, isVerified: true, services: ['Пломбирање', 'Вадење заби', 'Протетика', 'Белење заби'], coverImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&q=80&w=600', galleryImages: ['https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&q=80&w=600'] },
  { id: '2', name: 'Поликлиника Полог', slug: 'poliklinika-polog', category: 'Здравство, Медицина и Фармација', categorySlug: 'zdravstvo-medicina-farmacija', subcategory: 'Ординации и специјалисти', location: 'Гостивар', shortDescription: 'Комплетни здравствени услуги на едно место.', fullDescription: 'Широк спектар на медицински прегледи и дијагностика.', phone: '042 333 444', secondaryPhone: '075 111 222', website: 'https://poliklinikapolog.mk', facebook: 'https://facebook.com/poliklinikapolog', address: 'ул. Браќа Ѓиноски', workingHours: 'Пон-Нед: 24/7', isFeatured: true, isVerified: true, coverImage: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6f0d8?auto=format&fit=crop&q=80&w=600' },
  { id: '3', name: 'Градежништво Балкан', slug: 'gradeznistvo-balkan', category: 'Дом, Градба и Мајсторски Услуги', categorySlug: 'dom-gradba-majstorski-uslugi', subcategory: 'Градежни фирми и изведувачи', location: 'Врапчиште', shortDescription: 'Се на едно место за вашиот нов дом.', fullDescription: 'Од темел до покрив. Висококвалитетни градежни материјали.', phone: '071 555 666', address: 'Главен пат', workingHours: 'Пон-Саб: 07:00 - 18:00', isFeatured: true, isVerified: true, coverImage: 'https://images.unsplash.com/photo-1541888081691-0391d4e7dafa?auto=format&fit=crop&q=80&w=600' },
  { id: '4', name: 'Електро Сервис Сашо', slug: 'elektro-servis-sasho', category: 'Дом, Градба и Мајсторски Услуги', categorySlug: 'dom-gradba-majstorski-uslugi', subcategory: 'Водовод, електрика и молерисување', location: 'Гостивар', shortDescription: 'Брза интервенција и поправка на електрични инсталации.', fullDescription: 'Професионален електричар со 20 години искуство.', phone: '075 222 333', address: 'ул. Борче Јовановски', workingHours: '24/7 за итни интервенции', isFeatured: false, isVerified: false },
  { id: '5', name: 'Автосервис Тони', slug: 'avtoservis-toni', category: 'Авто-мото и Транспорт', categorySlug: 'avto-moto-transport', subcategory: 'Авто сервиси', location: 'Боговиње', shortDescription: 'Сервис и дијагностика за сите видови возила.', fullDescription: 'Комплетна поправка и компјутерска дијагностика.', phone: '071 999 888', address: 'Главен пат Боговиње', workingHours: 'Пон-Саб: 08:00 - 18:00', isFeatured: true, isVerified: true, coverImage: 'https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?auto=format&fit=crop&q=80&w=600' },
  { id: '6', name: 'AutoParts Plus', slug: 'autoparts-plus', category: 'Авто-мото и Транспорт', categorySlug: 'avto-moto-transport', subcategory: 'Автоделови и опрема', location: 'Гостивар', shortDescription: 'Оригинални и заменски авто делови.', fullDescription: 'Најголем избор на авто делови и масла по најповолни цени.', phone: '078 444 555', address: 'ул. ЈНА бр. 45', workingHours: 'Пон-Саб: 08:30 - 17:00', isFeatured: true, isVerified: true, coverImage: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&q=80&w=600' },
  { id: '7', name: 'Ресторан Мерак', slug: 'restoran-merak', category: 'Храна, Кафулиња и Угостителство', categorySlug: 'hrana-kafulinja-ugostitelstvo', subcategory: 'Ресторани', location: 'Гостивар', shortDescription: 'Традиционална македонска кујна и скара на ќумур.', fullDescription: 'Најубав амбиент и највкусна храна во градот.', phone: '042 111 222', facebook: 'https://facebook.com', address: 'ул. Мајор Чеде Филипоски', workingHours: '10:00 - 24:00', isFeatured: true, isVerified: true, coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=600' },
  { id: '8', name: 'Кафе Бар Плоштад', slug: 'kafe-bar-ploshtad', category: 'Храна, Кафулиња и Угостителство', categorySlug: 'hrana-kafulinja-ugostitelstvo', subcategory: 'Кафулиња и барови', location: 'Гостивар', shortDescription: 'Најубавото кафе во центарот на градот.', fullDescription: 'Опуштена атмосфера, одлична музика и врвно еспресо.', phone: '075 111 222', address: 'Плоштад Гоце Делчев', workingHours: '07:00 - 01:00', isFeatured: true, isVerified: false, coverImage: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=600' },
  { id: '9', name: 'Мебел Сити', slug: 'mebel-siti', category: 'Продавници, Трговија и Локални Производи', categorySlug: 'prodavnici-trgovija-lokalni-proizvodi', subcategory: 'Дом, подароци и декорации', location: 'Гостивар', shortDescription: 'Сè за вашиот дом.', fullDescription: 'Најголем изложбен салон за мебел и осветлување.', phone: '042 777 888', website: 'https://mebel-siti.mk', address: 'Индустриска зона', workingHours: '09:00 - 20:00', isFeatured: true, isVerified: true, coverImage: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=80&w=600' },
  { id: '10', name: 'Техно Маркет', slug: 'tehno-market', category: 'Продавници, Трговија и Локални Производи', categorySlug: 'prodavnici-trgovija-lokalni-proizvodi', subcategory: 'Техника, мобилни и електроника', location: 'Гостивар', shortDescription: 'Бела техника и електроника.', fullDescription: 'Телевизори, лаптопи, бела техника и паметни уреди.', phone: '042 333 111', address: 'ул. Гоце Делчев', workingHours: '09:00 - 21:00', isFeatured: false, isVerified: true },
  { id: '11', name: 'Hair Studio Elegance', slug: 'hair-studio-elegance', category: 'Убавина, Нега и Wellness', categorySlug: 'ubavina-nega-wellness', subcategory: 'Фризерски салони', location: 'Гостивар', shortDescription: 'Ексклузивен фризерски салон.', fullDescription: 'Професионална нега на коса, шишање, фарбање.', phone: '070 333 444', address: 'ул. Живко Брајковски', workingHours: '10:00 - 18:00', isFeatured: true, isVerified: false, coverImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=600' },
  { id: '12', name: 'Spa Centar Oaza', slug: 'spa-centar-oaza', category: 'Убавина, Нега и Wellness', categorySlug: 'ubavina-nega-wellness', subcategory: 'Масажа и wellness услуги', location: 'Гостивар', shortDescription: 'Релаксација, масажи и козметички третмани.', fullDescription: 'Уживајте во нашите масажи и третмани во смирувачка атмосфера.', phone: '071 888 777', address: 'ул. Вардарска', workingHours: '12:00 - 20:00', isFeatured: false, isVerified: true },
  { id: '13', name: 'Агенција Недвижности Плус', slug: 'agencija-nedviznosti-plus', category: 'Професионални Услуги и Агенции', categorySlug: 'profesionalni-uslugi-agencii', subcategory: 'Недвижности и агенции', location: 'Гостивар', shortDescription: 'Сигурен партнер за купување и продавање недвижности.', fullDescription: 'Најдобра понуда на станови, куќи и плацеви.', phone: '075 444 333', address: 'Булевар Браќа Ѓиноски', workingHours: '08:30 - 16:30', isFeatured: true, isVerified: true, coverImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=600' },
  { id: '14', name: 'Сметководствено Биро Баланс', slug: 'smetkovodstveno-biro-balans', category: 'Професионални Услуги и Агенции', categorySlug: 'profesionalni-uslugi-agencii', subcategory: 'Сметководство и финансии', location: 'Гостивар', shortDescription: 'Професионално сметководство за вашиот бизнис.', fullDescription: 'Водење на сметководство, советување за даноци.', phone: '076 111 555', address: 'Центар', workingHours: '08:00 - 16:00', isFeatured: false, isVerified: true },
  { id: '15', name: 'Едукативен Центар Знаење', slug: 'edukativen-centar-znaenje', category: 'Образование, Курсеви и Развој', categorySlug: 'obrazovanie-kursevi-razvoj', subcategory: 'Јазични школи', location: 'Гостивар', shortDescription: 'Курсеви по странски јазици и информатика.', fullDescription: 'Одобрени програми за сите возрасти.', phone: '070 999 000', address: 'ул. Кеј Вардар', workingHours: '16:00 - 21:00', isFeatured: true, isVerified: true },
  { id: '16', name: 'Авто Школа Волан', slug: 'avto-shkola-volan', category: 'Образование, Курсеви и Развој', categorySlug: 'obrazovanie-kursevi-razvoj', subcategory: 'Обуки и професионални курсеви', location: 'Гостивар', shortDescription: 'Обука за возачи со искусни инструктори.', fullDescription: 'Научете да возите безбедно. Повеќе од 15 години искуство.', phone: '071 222 111', address: 'Судска палата', workingHours: '09:00 - 18:00', isFeatured: false, isVerified: true },
  { id: '17', name: 'Фото Студио МК', slug: 'foto-studio-mk', category: 'Забава, Настани и Креативни Услуги', categorySlug: 'zabava-nastani-kreativni-uslugi', subcategory: 'Фото и видео услуги', location: 'Гостивар', shortDescription: 'Фотографирање и снимање свадби и прослави.', fullDescription: 'Вашите спомени зачувани на врвен начин.', phone: '078 999 888', instagram: 'https://instagram.com', address: 'Центар', workingHours: 'По договор', isFeatured: true, isVerified: true, coverImage: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&q=80&w=600' },
  { id: '18', name: 'Игротека Детски Свет', slug: 'igroteka-detski-svet', category: 'Забава, Настани и Креативни Услуги', categorySlug: 'zabava-nastani-kreativni-uslugi', subcategory: 'Игротеки и детски забави', location: 'Гостивар', shortDescription: 'Најзабавни родендени за вашите најмали.', fullDescription: 'Безбеден простор, аниматори и одлична забава.', phone: '075 555 444', address: 'ул. Дутлок', workingHours: '14:00 - 22:00', isFeatured: false, isVerified: false },
  { id: '19', name: 'Фитнес Клуб GymFit', slug: 'fitnes-klub-gymfit', category: 'Спорт, Рекреација и Активен Живот', categorySlug: 'sport-rekreacija-aktiven-zivot', subcategory: 'Фитнес центри и теретани', location: 'Гостивар', shortDescription: 'Најсовремена теретана и фитнес програми.', fullDescription: 'Професионални справи, групни тренинзи и лични тренери.', phone: '070 333 222', address: 'Спортска Сала', workingHours: '07:00 - 23:00', isFeatured: true, isVerified: true, coverImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600' },
  { id: '20', name: 'Спортска Опрема Sport+', slug: 'sportska-oprema-sport-plus', category: 'Спорт, Рекреација и Активен Живот', categorySlug: 'sport-rekreacija-aktiven-zivot', subcategory: 'Спортска опрема и облека', location: 'Гостивар', shortDescription: 'Облека и обувки за сите спортови.', fullDescription: 'Брендирани патики, тренерки и реквизити.', phone: '042 123 456', address: 'ул. ЈНА', workingHours: '09:00 - 20:00', isFeatured: false, isVerified: true },
];

export default async function handler(req: VercelRequest, res: VercelResponse) {
  setCors(res);
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Методот не е дозволен.' });
  if (!isAuthorized(req)) return unauthorized(res);

  const results: Record<string, any> = {};

  const tables = [
    { name: 'categories', rows: categories.map(frontendCategoryToDb) },
    { name: 'locations',  rows: locations.map(frontendLocationToDb) },
    { name: 'contacts',   rows: contacts.map(frontendContactToDb) },
    { name: 'articles',   rows: articles.map(frontendArticleToDb) },
    { name: 'profiles',   rows: profiles.map(r => frontendProfileToDb({ ...r, isPending: false, verificationStatus: 'unverified' })) },
  ];

  for (const { name, rows } of tables) {
    const { error } = await (supabaseAdmin as any)
      .from(name)
      .upsert(rows as any[], { onConflict: 'id', ignoreDuplicates: true });
    results[name] = error ? `❌ ${error.message}` : `✅ ${rows.length} records`;
  }

  return res.json({ success: true, results });
}
